server:
  port: 9901


spring:
  main:
    allow-bean-definition-overriding: true


  spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8
      username: root
      password: mysqladmin
      driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  shardingsphere:
    props:
      sql:
        show: true
    masterslave:



file:
saveLinuxPath: /tmp/store
saveWindowsPath: D:\\picture
