application:
  name: springboot-apsjp

server:
  port: 9901

spring:
  jpa:
    hibernate:
      ddl-auto: update
    shardingsphere:
      props:
        sql:
          show: true
      masterslave:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: mysqladmin
    driver-class-name: com.mysql.jdbc.Driver

#logback配置
#logging:
 # pattern:
  #  console: '%d -%msg%n'
 # path: D:/data/log/seller.log
  #level:
   # root: debug



file:
saveLinuxPath: /tmp/store
saveWindowsPath: D:\\picture

order:
  all:
    data:
      cron: 0 0 */1 * * ?
  update:
    data:
      cron:*/10 * * * * ?